### PR TITLE
Added option to automatically reconnect client on MQTT disconnect

### LINKED ISSUE #26: RuntimeError: unexpected disconnection
The client does not reconnect to the server if any unexpected error happened. I believe it's because of [this line](https://github.com/TheThingsNetwork/python-app-sdk/blob/7f2e8e618ed59bcacbb2370385b1f34ad02103e1/ttn/ttnmqtt.py#L101).

I removed this line in ttn python package and it worked fine.

### PR DESCRIPTION
**Pull request by gtmtg**
Fixes #26

### CODE REVIEW

**Review by egourlao — APPROVED** [review]
Looks great and clean, thanks for the work! Can you add documentation for `reconnect` in `DOCUMENTATION.md`? I'll happily merge it after that :)

**Comment by gtmtg** [comment]
Of course! Is `README.rst` a legacy file or does it need to be updated too? Seems like mostly a duplicate of `DOCUMENTATION.md`...

**Comment by egourlao** [comment]
`README.rst` is being used by `setuptools` to generate documentation for `pip`. If I remember correctly, though, `setuptools` is also Markdown-compatible, so there should be a way to use `DOCUMENTATION.md` to avoid double work. I'll look into it tomorrow - if you don't want to wait, a copypaste should be enough :)

**Comment by gtmtg** [comment]
@dotpy3 Just updated both files! Question: I made the parameter default to `False` to preserve the original behavior, but I'm wondering if we should make it default to `True` instead? I feel like that may be expected behavior.

Also, re: using Markdown in `setup.py`, seems like you can just pass the Markdown file directly instead of the reStructuredText. See https://github.com/pypa/python-packaging-user-guide/blob/master/source/guides/distributing-packages-using-setuptools.rst#readme-rst-readme-md

**Comment by gtmtg** [comment]
@dotpy3 Bump on this!

**Comment by egourlao** [comment]
Let's go for setting it to `True` indeed, I think we can agree that this is the expected behaviour :)

**Comment by gtmtg** [comment]
Done! Sorry for the delay. Good to go?

**Comment by egourlao** [comment]
Looks great! Thank you for your contribution :)

**Pull request merged**
